// <auto-generated />
namespace _2012206149.PER.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class prime : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(prime));
        
        string IMigrationMetadata.Id
        {
            get { return "201706071914397_prime"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
